version: "3.5"
services:

  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PATHS_DATA : /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD : admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - kafka_net

  prometheus:
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    container_name: prometheus
    hostname: prometheus
    ports:
      - "10000:9090"
    extra_hosts:
      - "kafka:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --log.level=debug"
    networks:
      - kafka_net

networks:
  kafka_net :
    name: kafka_net
    external: true
