global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-kafka1-1:7072', 'kafka-kafka2-1:7072', 'kafka-kafka3-1:7072']
