version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka_net      

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: >-
        -javaagent:/etc/jmx_exporter/jmx_exporter.jar=7072:/etc/jmx_exporter/config.yml
    volumes:
      - ./data/node1:/opt/kafka/data
      - ./jmx_exporter/jmx_exporter.jar:/etc/jmx_exporter/jmx_exporter.jar
      - ./jmx_exporter/config.yml:/etc/jmx_exporter/config.yml
    networks:
      - kafka_net      


  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29093

    hostname: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: >-
        -javaagent:/etc/jmx_exporter/jmx_exporter.jar=7072:/etc/jmx_exporter/config.yml
    volumes:
      - ./data/node2:/opt/kafka/data
      - ./jmx_exporter/jmx_exporter.jar:/etc/jmx_exporter/jmx_exporter.jar
      - ./jmx_exporter/config.yml:/etc/jmx_exporter/config.yml

    networks:
      - kafka_net
  
  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29094:29094
    hostname: kafka3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: >-
        -javaagent:/etc/jmx_exporter/jmx_exporter.jar=7072:/etc/jmx_exporter/config.yml
    volumes:
      - ./data/node3:/opt/kafka/data
      - ./jmx_exporter/jmx_exporter.jar:/etc/jmx_exporter/jmx_exporter.jar
      - ./jmx_exporter/config.yml:/etc/jmx_exporter/config.yml
    networks:
      - kafka_net

networks:
  kafka_net:
    name: kafka_net
