apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth:
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
  #  jsonData:
  #     graphiteVersion: "1.1"
  #     tlsAuth: true
  #     tlsAuthWithCACert: true
    # <string> json object of data that will be encrypted.
  #  secureJsonData:
  #    tlsCACert: "..."
  #    tlsClientCert: "..."
  #    tlsClientKey: "..."
    version: 1
    editable: true
